# Generated by Django 4.2.1 on 2023-06-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='country',
            new_name='pais',
        ),
    ]
