# Generated by Django 4.2.1 on 2023-06-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('numero_carne', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('correo_personal', models.CharField(max_length=100)),
                ('correo_institucional', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('promocion', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_grado', models.CharField(choices=[('Cedula de Ciudadania', 'Cedula de Ciudadania'), ('Cedula de Extranjeria', 'Cedula de Extranjeria'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Pasaporte', 'Pasaporte')], max_length=50)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Pregrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Posgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.egresado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='egresado',
            name='pregrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pregrado'),
        ),
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.egresado')),
                ('posgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.posgrado')),
            ],
        ),
    ]
