# Generated by Django 4.2.1 on 2023-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_egresado_pregrado_posgrado_laboral_egresado_pregrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='genero',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='tipo_grado',
            field=models.CharField(choices=[('Ceremony', 'Ceremony'), ('Window', 'Window')], max_length=50),
        ),
    ]
