# Generated by Django 4.2.1 on 2023-06-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_egresado_genero_alter_egresado_tipo_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libreria_libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('libreria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.libreria')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('año_publicacion', models.DateField()),
                ('precio', models.IntegerField()),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.autor')),
                ('editorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.editorial')),
            ],
        ),
        migrations.RemoveField(
            model_name='academico',
            name='egresado',
        ),
        migrations.RemoveField(
            model_name='academico',
            name='posgrado',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='pregrado',
        ),
        migrations.RemoveField(
            model_name='laboral',
            name='Egresado',
        ),
        migrations.RemoveField(
            model_name='laboral',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='posgrado',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='pregrado',
            name='facultad',
        ),
        migrations.DeleteModel(
            name='Academico',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Egresado',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Facultad',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
        migrations.DeleteModel(
            name='Laboral',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Posgrado',
        ),
        migrations.DeleteModel(
            name='Pregrado',
        ),
        migrations.AddField(
            model_name='libreria_libro',
            name='libro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.libro'),
        ),
    ]
