# Generated by Django 4.2.1 on 2023-06-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_egresado_genero_alter_egresado_tipo_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='pregrado',
        ),
        migrations.RemoveField(
            model_name='laboral',
            name='Egresado',
        ),
        migrations.RemoveField(
            model_name='laboral',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='posgrado',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='pregrado',
            name='facultad',
        ),
        migrations.DeleteModel(
            name='Academico',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Egresado',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Facultad',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
        migrations.DeleteModel(
            name='Laboral',
        ),
        migrations.DeleteModel(
            name='Posgrado',
        ),
        migrations.DeleteModel(
            name='Pregrado',
        ),
    ]
